repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    types: [python]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
  - id: ruff
    types: [python]
- repo: local
  hooks:
  - id: django-test
    name: django-test
    entry: python sky_sync\\manage.py test
    pass_filenames: false
    language: system
  - id: commit-msg
    name: Make sure that commit message starts with [FEAT] or [FIX]
    entry: '^\[FEAT\]|^\[FIX\]'
    language: pygrep
    args: [ --negate ]
    stages: [ commit-msg ]
